### PR TITLE
downgrade jquery to version 2.2.4 as bootstrap need a version lower t…

### PR DESCRIPTION
**Pull request by ziedmahdi**
This will solve #90

### CODE REVIEW

**Comment by mrvautin** [comment]
You are correct, I never noticed that. 

Did you see any issues with using jQuery 3.x?

**Comment by ziedmahdi** [comment]
Yes, every thing related to bootstrap is not working.

On the console you will find an error like this one:
`bootstrap.min.js:6 Uncaught Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3`

**Comment by mrvautin** [comment]
I never noticed it. Thanks for contributing.

**Comment by ziedmahdi** [comment]
Not at all.

**Pull request merged**
