### PR TITLE
Better code format / Added Russian locale

### PR DESCRIPTION
**Pull request by TemaSM**
* Code cleanup (if statements), removed unnecessary braces
* Code formating using JS CodeStyle
+ Added Russian locale
P.S> Everything tested and works

### CODE REVIEW

**Comment by mrvautin** [comment]
Looks good! Thanks for contributing!

**Comment by TemaSM** [comment]
How about if I will fix and redesign UI?
It's not so useful, because of big fonts sizes and and stacking content in the blocks.
And I gonna implement automatic locale selection, based on Accept-Language header if locale didn't configured by app.js.

**Comment by mrvautin** [comment]
Sounds good. Submit a PR I will have a look.

Not sure which font is too big but always willing to take feedback.

**Comment by TemaSM** [comment]
What about assets? May I use CDN or should place js & css libs locally or via Bower?

And how about to create npm postinstall script, which will manually move adminMongo from node_modules to root dir, from where npm install called? I will try to make this script and send PR.

**Comment by mrvautin** [comment]
I've deliberately avoided CDN as some people run without access to Internet etc. Some assets (queerly and bootstrap) are installed by Npm now.

Sounds good regarding the post script.

**Pull request merged**
