### PR TITLE
Update editor.js

### PR DESCRIPTION
**Pull request by lefdilia**
"success" and "error" are deprecated

### CODE REVIEW

**Comment by mrvautin** [comment]
Ok I see what you mean now. The success/error syntax is also used heavily in 'adminMongo.js'.

**Comment by lefdilia** [comment]
Great, but i guess you need a big update for that !!

**Comment by mrvautin** [comment]
Yes. I think doing one big change would be preferred.

**Comment by lefdilia** [comment]
👍

**Comment by mrvautin** [comment]
Updated in commit 4641afa91c7f5690e6750fb979a9100f9d7af9cd.

**Pull request closed without merging**
