### PR TITLE
Search Modal-> DropDown Select Options for Key/Field

### PR DESCRIPTION
**Pull request by destromas1**

### CODE REVIEW

**Comment by destromas1** [comment]
image

**Comment by destromas1** [comment]
image

**Comment by destromas1** [comment]
@mrvautin Plz Check

**Comment by mrvautin** [comment]
Great idea! I'm a bit busy but I will have a look and test over the next few days.

**Comment by destromas1** [comment]
Sure Thanks!

**Comment by mrvautin** [comment]
Your changes work fine. I have a few comments though:

* Line 63 of `public/js/adminMongo.js` has a comment which needs removing.
* Line 1015 of `routes/index.js` has a console.log which needs removing
* Line 1022, 1025, 1026 of `routes/index.js` has a typo in the variable name. Should be: resultForFields or even better something about what it does. Eg: simpleSearchFields
* Line  124 of `views/layouts/layout.hbs` has a comment which needs removing

**Comment by destromas1** [comment]
Sure I will Do

**Comment by destromas1** [comment]
@mrvautin Plz Check

**Pull request merged**
