### PR TITLE
+ NPM postinstall script

### PR DESCRIPTION
**Pull request by TemaSM**
Script for adminMongo installation/copying process automation

### CODE REVIEW

**Comment by mrvautin** [comment]
Looks good. What are your thoughts on removing the files after the copy?

**Comment by TemaSM** [comment]
Yeah, good idea, but we should additionaly add new dependecy - `rimraf` module.
If you you don't against this, I will code file removing behaviour and gonna move `npm_postinstall.js` file into new folder named `lib`, which will be deleted right after install too.

**Comment by mrvautin** [comment]
No worries. Adding that module is fine.

**Comment by TemaSM** [comment]
Eveyrthing works - tested, but if someone will clone repository and type `npm install`, npm will launch postinstall script and here is a problem - we already in root dir, so we don't need to start it at all.
Anyway it will be fixed soon. Meanwhile you may merge PR.

**Comment by mrvautin** [comment]
I think the check for `node_modules` dir would be needed before merging as some users wont be able to simply run `npm install` from within the `adminMongo` dir after install.

Maybe something like this?
```
if (!fs.existsSync(path.join(currentDir, 'node_modules'))){
```
In here:
```
// __dirname = <root>/node_modules/admin-mongo/lib/
var currentDir = path.join(__dirname, './../'); // <root>/node_modules/admin-mongo/
var destinationDir = path.join(currentDir, './../../'); // <root>
var toCleanDir = path.join(currentDir, './../admin-mongo/'); // Delete all children and the parent

// detects if 'npm install' has been ran from within the <root> adminMongo directory
if (!fs.existsSync(path.join(currentDir, 'node_modules'))){
    console.log('\x1b[1m-= adminMongo Installation wizard =-');
    console.log('\x1b[1m--------------------------------------------------------');
    console.log('\x1b[33mCopying installed adminMongo from \n\x1b[36m' + currentDir + '\x1b[33m\nto \n\x1b[36m' + path.resolve(destinationDir) + '\x1b[0m');
```

**Comment by TemaSM** [comment]
Yeah, you right. I had already implementes this check. Now we can handle how script waa triggered:
1) By standard install process 'npm i admin-mongo'
2) By installing deps after clonning repo. 'npm install'
3) By updating deps using 'npm update'
But right now have crazy glitch with output wgen everything done. Gonna fix it today.

**Comment by mrvautin** [comment]
It still has a few issues. When I pull/clone from your repo and then run `npm install` everything gets blown away. I think we still need to support installs from people who want to clone the repo and install (which is a heap of people according to Github stats).

I'm just having a look at the checks now.

**Comment by TemaSM** [comment]
Wow, so strange, cause I tested everything... Will try again :yum:

**Comment by TemaSM** [comment]
Everything works fine.

```bash
Artem@MANAGER4-PC D:\ToInstall
> git clone https://github.com/mrvautin/adminMongo.git && cd adminMongo && npm install &
& npm start
Cloning into 'adminMongo'...
remote: Counting objects: 1278, done.
remote: Compressing objects: 100% (21/21), done.
emote: Total 1278 (delta 8), reused 0 (delta 0), pack-reused 1257
Receiving objects: 100% (1278/1278), 2.57 MiB | 855.00 KiB/s, done.
Resolving deltas: 100% (669/669), done.
Checking connectivity... done.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node r
. Use 'npm ls graceful-fs' to find it in the tree.
[      ............] | fetchMetadata: verb afterAdd C:\Users\Artem\AppData\Roaming\npm-c
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest
 version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment
/to-iso-string instead.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid
 a RegExp DoS issue

> electron-prebuilt@1.2.8 postinstall D:\ToInstall\adminMongo\node_modules\electron-prebuilt
> node install.js

admin-mongo@0.0.14 D:\ToInstall\adminMongo
+-- async@1.5.2
+-- body-parser@1.13.3
| +-- bytes@2.1.0
| +-- content-type@1.0.2
| +-- debug@2.2.0
| +-- depd@1.0.1
| +-- http-errors@1.3.1
| | +-- inherits@2.0.1
| | `-- statuses@1.3.0
| +-- iconv-lite@0.4.11
| +-- on-finished@2.3.0
| | `-- ee-first@1.1.1
| +-- qs@4.0.0
| +-- raw-body@2.1.7
| | +-- bytes@2.4.0
| | +-- iconv-lite@0.4.13
| | `-- unpipe@1.0.0
| `-- type-is@1.6.13
|   +-- media-typer@0.3.0
|   `-- mime-types@2.1.11
|     `-- mime-db@1.23.0
+-- bootstrap@3.3.6
+-- chai@3.5.0
| +-- assertion-error@1.0.2
| +-- deep-eql@0.1.3
| | `-- type-detect@0.1.1
| `-- type-detect@1.0.0
+-- colors@1.1.2
+-- config@1.21.0
| `-- json5@0.4.0
+-- cookie-parser@1.3.5
| +-- cookie@0.1.3
| `-- cookie-signature@1.0.6
+-- electron-prebuilt@1.2.8
| +-- electron-download@2.1.2
| | +-- home-path@1.0.3
| | +-- minimist@1.2.0
| | +-- mv@2.1.1
| | | +-- ncp@2.0.0
| | | `-- rimraf@2.4.5
| | |   `-- glob@6.0.4
| | +-- nugget@1.6.2
| | | +-- minimist@1.2.0
| | | +-- pretty-bytes@1.0.4
| | | | +-- get-stdin@4.0.1
| | | | `-- meow@3.7.0
| | | |   +-- camelcase-keys@2.1.0
| | | |   +-- loud-rejection@1.6.0
| | | |   | +-- currently-unhandled@0.4.1
| | | |   | | `-- array-find-index@1.0.1
| | | |   | `-- signal-exit@3.0.0
| | | |   +-- map-obj@1.0.1
| | | |   +-- minimist@1.2.0
| | | |   +-- normalize-package-data@2.3.5
| | | |   | +-- hosted-git-info@2.1.5
| | | |   | +-- is-builtin-module@1.0.0
| | | |   | | `-- builtin-modules@1.1.1
| | | |   | `-- validate-npm-package-license@3.0.1
| | | |   |   +-- spdx-correct@1.0.2
| | | |   |   | `-- spdx-license-ids@1.2.1
| | | |   |   `-- spdx-expression-parse@1.0.2
| | | |   |     `-- spdx-exceptions@1.0.5
| | | |   +-- object-assign@4.1.0
| | | |   +-- read-pkg-up@1.0.1
| | | |   | +-- find-up@1.1.2
| | | |   | | `-- path-exists@2.1.0
| | | |   | `-- read-pkg@1.1.0
| | | |   |   +-- load-json-file@1.1.0
| | | |   |   | +-- graceful-fs@4.1.4
| | | |   |   | +-- parse-json@2.2.0
| | | |   |   | | `-- error-ex@1.3.0
| | | |   |   | |   `-- is-arrayish@0.2.1
| | | |   |   | +-- pify@2.3.0
| | | |   |   | `-- strip-bom@2.0.0
| | | |   |   |   `-- is-utf8@0.2.1
| | | |   |   `-- path-type@1.1.0
| | | |   |     `-- graceful-fs@4.1.4
| | | |   +-- redent@1.0.0
| | | |   | +-- indent-string@2.1.0
| | | |   | | `-- repeating@2.0.1
| | | |   | |   `-- is-finite@1.0.1
| | | |   | `-- strip-indent@1.0.1
| | | |   `-- trim-newlines@1.0.0
| | | +-- progress-stream@1.2.0
| | | | +-- speedometer@0.1.4
| | | | `-- through2@0.2.3
| | | |   +-- readable-stream@1.1.14
| | | |   `-- xtend@2.1.2
| | | |     `-- object-keys@0.4.0
| | | +-- single-line-log@0.4.1
| | | `-- throttleit@0.0.2
| | +-- path-exists@1.0.0
| | `-- rc@1.1.6
| |   +-- deep-extend@0.4.1
| |   +-- minimist@1.2.0
| |   `-- strip-json-comments@1.0.4
| `-- extract-zip@1.5.0
|   +-- concat-stream@1.5.0
|   | +-- readable-stream@2.0.6
|   | | +-- isarray@1.0.0
|   | | +-- process-nextick-args@1.0.7
|   | | `-- util-deprecate@1.0.2
|   | `-- typedarray@0.0.6
|   +-- debug@0.7.4
|   +-- mkdirp@0.5.0
|   | `-- minimist@0.0.8
|   `-- yauzl@2.4.1
|     `-- fd-slicer@1.0.1
|       `-- pend@1.2.0
+-- express@4.13.4
| +-- accepts@1.2.13
| | `-- negotiator@0.5.3
| +-- array-flatten@1.1.1
| +-- content-disposition@0.5.1
| +-- cookie@0.1.5
| +-- depd@1.1.0
| +-- escape-html@1.0.3
| +-- etag@1.7.0
| +-- finalhandler@0.4.1
| +-- fresh@0.3.0
| +-- merge-descriptors@1.0.1
| +-- methods@1.1.2
| +-- parseurl@1.3.1
| +-- path-to-regexp@0.1.7
| +-- proxy-addr@1.0.10
| | +-- forwarded@0.1.0
| | `-- ipaddr.js@1.0.5
| +-- range-parser@1.0.3
| +-- send@0.13.1
| | +-- depd@1.1.0
| | +-- destroy@1.0.4
| | +-- mime@1.3.4
| | `-- statuses@1.2.1
| +-- serve-static@1.10.3
| | `-- send@0.13.2
| |   +-- depd@1.1.0
| |   `-- statuses@1.2.1
| +-- utils-merge@1.0.0
| `-- vary@1.0.1
+-- express-handlebars@2.0.1
| +-- glob@5.0.15
| | +-- inflight@1.0.5
| | | `-- wrappy@1.0.2
| | +-- minimatch@3.0.2
| | | `-- brace-expansion@1.1.6
| | |   +-- balanced-match@0.4.2
| | |   `-- concat-map@0.0.1
| | +-- once@1.3.3
| | `-- path-is-absolute@1.0.0
| +-- graceful-fs@3.0.8
| +-- handlebars@3.0.3
| | +-- optimist@0.6.1
| | | +-- minimist@0.0.10
| | | `-- wordwrap@0.0.3
| | +-- source-map@0.1.43
| | | `-- amdefine@1.0.0
| | `-- uglify-js@2.3.6
| |   +-- async@0.2.10
| |   `-- optimist@0.3.7
| +-- object.assign@1.1.1
| | `-- object-keys@1.0.11
| `-- promise@6.1.0
|   `-- asap@1.0.0
+-- express-session@1.14.0
| +-- cookie@0.3.1
| +-- crc@3.4.0
| +-- depd@1.1.0
| +-- on-headers@1.0.1
| `-- uid-safe@2.1.1
|   +-- base64-url@1.2.2
|   `-- random-bytes@1.0.0
+-- font-awesome@4.6.3
+-- hbs@3.1.1
| +-- handlebars@3.0.0
| `-- walk@2.2.1
|   `-- forEachAsync@2.2.1
|     `-- sequence@2.2.1
+-- i18n-2@0.6.3
| `-- sprintf@0.1.5
+-- jquery@2.2.4
+-- jsdom@9.4.1
| +-- abab@1.0.3
| +-- acorn@2.7.0
| +-- acorn-globals@1.0.9
| | `-- acorn@2.7.0
| +-- array-equal@1.0.0
| +-- cssom@0.3.1
| +-- cssstyle@0.2.36
| +-- escodegen@1.8.0
| | +-- esprima@2.7.2
| | +-- estraverse@1.9.3
| | +-- esutils@2.0.2
| | +-- optionator@0.8.1
| | | +-- deep-is@0.1.3
| | | +-- fast-levenshtein@1.1.4
| | | +-- levn@0.3.0
| | | +-- prelude-ls@1.1.2
| | | +-- type-check@0.3.2
| | | `-- wordwrap@1.0.0
| | `-- source-map@0.2.0
| +-- iconv-lite@0.4.13
| +-- nwmatcher@1.3.8
| +-- parse5@1.5.1
| +-- request@2.73.0
| | +-- aws-sign2@0.6.0
| | +-- aws4@1.4.1
| | +-- bl@1.1.2
| | | `-- readable-stream@2.0.6
| | |   `-- isarray@1.0.0
| | +-- caseless@0.11.0
| | +-- combined-stream@1.0.5
| | | `-- delayed-stream@1.0.0
| | +-- extend@3.0.0
| | +-- forever-agent@0.6.1
| | +-- form-data@1.0.0-rc4
| | +-- har-validator@2.0.6
| | | +-- chalk@1.1.3
| | | | +-- ansi-styles@2.2.1
| | | | +-- escape-string-regexp@1.0.5
| | | | +-- has-ansi@2.0.0
| | | | `-- supports-color@2.0.0
| | | +-- commander@2.9.0
| | | | `-- graceful-readlink@1.0.1
| | | +-- is-my-json-valid@2.13.1
| | | | +-- generate-function@2.0.0
| | | | +-- generate-object-property@1.2.0
| | | | | `-- is-property@1.0.2
| | | | +-- jsonpointer@2.0.0
| | | | `-- xtend@4.0.1
| | | `-- pinkie-promise@2.0.1
| | |   `-- pinkie@2.0.4
| | +-- hawk@3.1.3
| | | +-- boom@2.10.1
| | | +-- cryptiles@2.0.5
| | | +-- hoek@2.16.3
| | | `-- sntp@1.0.9
| | +-- http-signature@1.1.1
| | | +-- assert-plus@0.2.0
| | | +-- jsprim@1.3.0
| | | | +-- extsprintf@1.0.2
| | | | +-- json-schema@0.2.2
| | | | `-- verror@1.3.6
| | | `-- sshpk@1.8.3
| | |   +-- asn1@0.2.3
| | |   +-- assert-plus@1.0.0
| | |   +-- dashdash@1.14.0
| | |   | `-- assert-plus@1.0.0
| | |   +-- ecc-jsbn@0.1.1
| | |   +-- getpass@0.1.6
| | |   | `-- assert-plus@1.0.0
| | |   +-- jodid25519@1.0.2
| | |   +-- jsbn@0.1.0
| | |   `-- tweetnacl@0.13.3
| | +-- is-typedarray@1.0.0
| | +-- isstream@0.1.2
| | +-- json-stringify-safe@5.0.1
| | +-- node-uuid@1.4.7
| | +-- oauth-sign@0.8.2
| | +-- qs@6.2.1
| | +-- stringstream@0.0.5
| | `-- tunnel-agent@0.4.3
| +-- sax@1.2.1
| +-- symbol-tree@3.1.4
| +-- tough-cookie@2.2.2
| +-- webidl-conversions@3.0.1
| +-- whatwg-url@3.0.0
| | `-- tr46@0.0.3
| `-- xml-name-validator@2.0.1
+-- lodash@4.13.1
+-- mocha@2.5.3
| +-- commander@2.3.0
| +-- diff@1.4.0
| +-- escape-string-regexp@1.0.2
| +-- glob@3.2.11
| | `-- minimatch@0.3.0
| |   +-- lru-cache@2.7.3
| |   `-- sigmund@1.0.1
| +-- growl@1.9.2
| +-- jade@0.26.3
| | +-- commander@0.6.1
| | `-- mkdirp@0.3.0
| +-- mkdirp@0.5.1
| | `-- minimist@0.0.8
| +-- supports-color@1.2.0
| `-- to-iso-string@0.0.2
+-- mocha-jsdom@1.1.0
+-- mongo-uri@0.1.2
+-- mongodb@2.2.4
| +-- es6-promise@3.0.2
| +-- mongodb-core@2.0.6
| | +-- bson@0.5.2
| | `-- require_optional@1.0.0
| |   +-- resolve-from@2.0.0
| |   `-- semver@5.3.0
| `-- readable-stream@1.0.31
|   +-- core-util-is@1.0.2
|   +-- isarray@0.0.1
|   `-- string_decoder@0.10.31
+-- mongodb-extended-json@1.7.0
| +-- bson@0.4.23
| +-- event-stream@3.3.4
| | +-- duplexer@0.1.1
| | +-- from@0.1.3
| | +-- map-stream@0.1.0
| | +-- pause-stream@0.0.11
| | +-- split@0.3.3
| | `-- stream-combiner@0.0.4
| +-- JSONStream@1.1.3
| | +-- jsonparse@1.2.0
| | `-- through@2.3.8
| +-- lodash.isfunction@3.0.8
| +-- lodash.transform@3.0.4
| | +-- lodash._arrayeach@3.0.0
| | +-- lodash._basecallback@3.3.1
| | | +-- lodash._baseisequal@3.0.7
| | | +-- lodash._bindcallback@3.0.1
| | | `-- lodash.pairs@3.0.1
| | +-- lodash._basecreate@3.0.3
| | +-- lodash._basefor@3.0.3
| | +-- lodash.isarray@3.0.4
| | +-- lodash.istypedarray@3.0.6
| | `-- lodash.keys@3.1.2
| |   +-- lodash._getnative@3.9.1
| |   `-- lodash.isarguments@3.0.8
| +-- moment@2.14.1
| `-- raf@3.2.0
|   `-- performance-now@0.2.0
+-- morgan@1.6.1
| `-- basic-auth@1.0.4
+-- nconf@0.8.4
| +-- ini@1.3.4
| +-- secure-keys@1.0.0
| `-- yargs@3.32.0
|   +-- camelcase@2.1.1
|   +-- cliui@3.2.0
|   | +-- strip-ansi@3.0.1
|   | | `-- ansi-regex@2.0.0
|   | `-- wrap-ansi@2.0.0
|   +-- decamelize@1.2.0
|   +-- os-locale@1.4.0
|   | `-- lcid@1.0.0
|   |   `-- invert-kv@1.0.0
|   +-- string-width@1.0.1
|   | +-- code-point-at@1.0.0
|   | | `-- number-is-nan@1.0.0
|   | `-- is-fullwidth-code-point@1.0.0
|   +-- window-size@0.1.4
|   `-- y18n@3.2.1
+-- nedb@1.8.0
| +-- async@0.2.10
| +-- binary-search-tree@0.2.5
| +-- localforage@1.4.2
| | `-- lie@3.0.2
| |   +-- es3ify@0.1.4
| |   | +-- esprima-fb@3001.1.0-dev-harmony-fb
| |   | `-- jstransform@3.0.0
| |   |   +-- base62@0.1.1
| |   |   `-- source-map@0.1.31
| |   +-- immediate@3.0.5
| |   +-- inline-process-browser@1.0.0
| |   | +-- falafel@1.2.0
| |   | | +-- acorn@1.2.2
| |   | | `-- foreach@2.0.5
| |   | `-- through2@0.6.5
| |   |   `-- readable-stream@1.0.34
| |   `-- unreachable-branch-transform@0.3.0
| |     +-- esmangle-evaluator@1.0.1
| |     `-- recast@0.10.43
| |       +-- ast-types@0.8.15
| |       +-- esprima-fb@15001.1001.0-dev-harmony-fb
| |       +-- private@0.1.6
| |       `-- source-map@0.5.6
| `-- underscore@1.4.4
+-- serve-favicon@2.3.0
| `-- ms@0.7.1
`-- supertest@1.2.0
  `-- superagent@1.8.3
    +-- component-emitter@1.2.1
    +-- cookiejar@2.0.6
    +-- form-data@1.0.0-rc3
    +-- formidable@1.0.17
    +-- qs@2.3.3
    +-- readable-stream@1.0.27-1
    `-- reduce-component@1.0.1


> admin-mongo@0.0.14 start D:\ToInstall\adminMongo
> node app.js

(node:9144) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
adminMongo listening on host: http://0.0.0.0:1234
```

**Comment by mrvautin** [comment]
That is my repo (without the preinstall merged), I was testing using your repo: `git clone git://github.com/TemaSM/adminMongo.git`

**Comment by mrvautin** [comment]
I think we need to check for the `admin-mongo` directory within the `./../node_modules/` directory. Eg: `path.join('./../', 'node_modules','admin-mongo')`. If it exists, we call `Install()` else we exit. This should mean it will only run when first installed from NPM.

**Comment by TemaSM** [comment]
*Updated my previous comment

**Comment by TemaSM** [comment]
https://github.com/TemaSM/adminMongo/blob/master/lib/npm_postinstall.js#L26

**Comment by mrvautin** [comment]
Hmm. I tried again and it worked. Not sure what happened the first time.

I will merge, version bump and re-publish to NPM.

**Comment by TemaSM** [comment]
Cool :smiley:

**Comment by mrvautin** [comment]
All done. I still can't believe this is not a built in feature of NPM cli. Amazes me you have to do these work arounds for something so simple.

Good work though!

**Pull request merged**
