### PR TITLE
Update layout.hbs

### PR DESCRIPTION
**Pull request by lefdilia**
downgrade JQuery to 2.2.4

### CODE REVIEW

**Comment by mrvautin** [comment]
Jquery is loaded via NPM and is already version 2.x in latest commit.

**Comment by lefdilia** [comment]
i don't think so,  npm load the latest version of JQuery

**_/*! jQuery v3.1.0 | (c) jQuery Foundation | jquery.org/license */_**

**Comment by mrvautin** [comment]
Shouldn't be. See PR: https://github.com/mrvautin/adminMongo/pull/91

**Comment by lefdilia** [comment]
i try to update the code to the worked version , i found those problems, so i think that maybe other need help ^^

**Comment by mrvautin** [comment]
We would prefer not to load dependencies from CDN in an application like this which is often used locally and without outside internet access.

**Comment by lefdilia** [comment]
okay so to prevent those problems, you can keep the latest version of JQuery and change "success" && "error" callbacks on "editor.js"

**Comment by mrvautin** [comment]
The latest version of Bootstrap now supports jQuery 3.x. After a little testing, we will be upgrading both jQuery and Bootstrap in package.json.

**Comment by mrvautin** [comment]
Changed in commit: 4641afa91c7f5690e6750fb979a9100f9d7af9cd.

**Pull request closed without merging**
